Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosRulez.SlickCarousel:
            - 'NodeTypes/*'
      defaultLanguage: 'de'
    nodeTypes:
      groups:
        slick:
          position: 'end'
          label: 'Slick'
    fusion:
      autoInclude:
        NeosRulez.SlickCarousel: true
NeosRulez:
  SlickCarousel:
    slickAllOver: true # Enable this if you want to use the Slick Component in your own afx template